# Generated by Django 3.2.16 on 2023-01-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=None, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'User')], default=2),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Credit_card',
            fields=[
                ('credit_card_num', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('expire_date', models.DateField()),
                ('masked_num', models.CharField(max_length=3)),
                ('limit', models.IntegerField()),
                ('curr_balance', models.DecimalField(decimal_places=2, default=50000, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAuth.company')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAuth.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appAuth.company'),
        ),
    ]
