# Generated by Django 3.2.16 on 2023-01-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0002_auto_20230118_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card',
            name='curr_balance',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=7),
        ),
    ]
