# Generated by Django 3.2.16 on 2023-01-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0003_alter_credit_card_curr_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together={('name', 'company')},
        ),
    ]
